MessageComponent: Add better json type exception (#3176)
Currently in MessageComponentConverter, the error on unknown type is
System.ArgumentNullException: Value cannot be null. (Parameter 'target')

This is because PopulateObject() doesn't allow a null target, but we
don't have a default case on the switch statement.